/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiParseDialog: typeof import('./components/AiParseDialog.vue')['default']
    AiReportDialog: typeof import('./components/AiReportDialog.vue')['default']
    CesiumStationScene: typeof import('./components/CesiumStationScene.vue')['default']
    CesiumViewer: typeof import('./components/CesiumViewer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTag: typeof import('element-plus/es')['ElTag']
    ErrorBoundary: typeof import('./components/ErrorBoundary.vue')['default']
    FtthMap: typeof import('./components/FtthMap.vue')['default']
    FtthPlanner: typeof import('./components/FtthPlanner.vue')['default']
    FtthTables: typeof import('./components/FtthTables.vue')['default']
    MarkdownView: typeof import('./components/MarkdownView.vue')['default']
    ProjectManagementUI: typeof import('./components/ProjectManagementUI.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkflowGuide: typeof import('./components/WorkflowGuide.vue')['default']
  }
}
